# Generated by Django 4.2.7 on 2024-05-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('dataNasc', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
            ],
        ),
    ]
