# Generated by Django 4.2.7 on 2024-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='googleId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
