# Generated by Django 4.2.7 on 2024-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pizzarias',
            name='cnpj',
            field=models.CharField(blank=True, default=None, max_length=14),
        ),
    ]
