# Generated by Django 4.2.7 on 2024-05-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_cpf_alter_pizzarias_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzarias',
            old_name='name',
            new_name='nome',
        ),
    ]
