# Generated by Django 4.2.7 on 2024-05-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_id_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='cidadde',
            new_name='cidade',
        ),
    ]
