# Generated by Django 4.2.7 on 2024-05-24 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_cidadde_endereco_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pizzarias')),
            ],
        ),
    ]
