# Generated by Django 4.2.7 on 2024-05-27 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_endereco_complemento_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('produtos', models.JSONField()),
                ('quantidade', models.IntegerField()),
                ('precoInical', models.FloatField()),
                ('precoFinal', models.FloatField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('pizzaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pizzarias')),
            ],
        ),
    ]
