# Generated by Django 4.2.7 on 2024-05-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='precoInical',
            new_name='precoInicial',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='quantidade',
        ),
    ]
