# Generated by Django 4.2.7 on 2024-05-29 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_precoinical_pedidos_precoinicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pizzaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzaria', to=settings.AUTH_USER_MODEL),
        ),
    ]
