# Generated by Django 4.2.7 on 2024-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_pedidos_cliente_alter_pedidos_pizzaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='preco',
        ),
        migrations.AddField(
            model_name='produtos',
            name='venda',
            field=models.JSONField(default={'Estatos': 'Não informado'}),
        ),
    ]
