# Generated by Django 4.2.7 on 2024-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pedidos_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='venda',
        ),
        migrations.AddField(
            model_name='produtos',
            name='opcoes',
            field=models.JSONField(default=dict),
        ),
    ]
