# Generated by Django 4.2.7 on 2024-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_produtos_venda_produtos_opcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='Pendente', max_length=30),
        ),
    ]
