# Generated by Django 4.2.7 on 2024-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_pedidos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(default='Pendente', max_length=30),
        ),
    ]
