# Generated by Django 5.0.6 on 2024-06-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_pizzarias_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzarias',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
